import React,{Component} from "react";
import NavbarSongs from "./NavbarSongs";
import './Songs.css';
// import {SongsData} from './SongsMain'
import Divider from "./Divider";

export class Songs extends Component{

  DataMusic = [
    
    {
      "SongID": "......And Roses And RosesAndy Williams",
      "Performer": "Andy Williams",
      "Song": "......And Roses And Roses",
      "spotify_genre": "['adult standards', 'brill building pop', 'easy listening', 'mellow gold']",
      "spotify_track_id": "3tvqPPpXyIgKrm4PR9HCf0",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/cef4883cfd1e0e5312be7ccce98176cff46d7879?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "166106",
      "spotify_track_explicit": "0",
      "spotify_track_album": "The Essential Andy Williams",
      "danceability": "0.154",
      "energy": "0.185",
      "key": "5",
      "loudness": "-14.063",
      "mode": "1",
      "speechiness": "0.0315",
      "acousticness": "0.911",
      "instrumentalness": "0.000267",
      "liveness": "0.112",
      "valence": "0.15",
      "tempo": "83.969",
      "time_signature": "4",
      "spotify_track_popularity": "38"
    },
    
    {
      "SongID": "...Baby One More TimeBritney Spears",
      "Performer": "Britney Spears",
      "Song": "...Baby One More Time",
      "spotify_genre": "['dance pop', 'pop', 'post-teen pop']",
      "spotify_track_id": "3MjUtNVVq3C8Fn0MP3zhXa",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/da2134a161f1cb34d17c2d6d7e77cc93d1c1e6f7?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "211066",
      "spotify_track_explicit": "0",
      "spotify_track_album": "...Baby One More Time (Digital Deluxe Version)",
      "danceability": "0.759",
      "energy": "0.699",
      "key": "0",
      "loudness": "-5.745",
      "mode": "0",
      "speechiness": "0.0307",
      "acousticness": "0.202",
      "instrumentalness": "0.000131",
      "liveness": "0.443",
      "valence": "0.907",
      "tempo": "92.96",
      "time_signature": "4",
      "spotify_track_popularity": "77"
    },
    
    {
      "SongID": "'65 Love AffairPaul Davis",
      "Performer": "Paul Davis",
      "Song": "'65 Love Affair",
      "spotify_genre": "['album rock', 'bubblegum pop', 'country rock', 'folk rock', 'mellow gold', 'new wave pop', 'soft rock', 'yacht rock']",
      "spotify_track_id": "5nBp8F6tekSrnFg8G2Pvug",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/a701445830ecacfb521200da9507753586200453?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "219813",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Radio Hits Of the '80s",
      "danceability": "0.647",
      "energy": "0.686",
      "key": "2",
      "loudness": "-4.247",
      "mode": "0",
      "speechiness": "0.0274",
      "acousticness": "0.432",
      "instrumentalness": "0.00000619",
      "liveness": "0.133",
      "valence": "0.952",
      "tempo": "155.697",
      "time_signature": "4",
      "spotify_track_popularity": "40"
    },




    
    {
      "SongID": "('til) I Kissed YouThe Everly Brothers",
      "Performer": "The Everly Brothers",
      "Song": "('til) I Kissed You",
      "spotify_genre": "['adult standards', 'brill building pop', 'bubblegum pop', 'folk rock', 'lounge', 'mellow gold', 'rock-and-roll', 'rockabilly', 'sunshine pop']",
      "spotify_track_id": "2erTdgDOZmjJNaNhjhWXhJ",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/c1719c80d7145e735caba90b0d2a1a77ea8827b2?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "146066",
      "spotify_track_explicit": "0",
      "spotify_track_album": "The Very Best of The Everly Brothers",
      "danceability": "0.518",
      "energy": "0.432",
      "key": "10",
      "loudness": "-11.689",
      "mode": "0",
      "speechiness": "0.0459",
      "acousticness": "0.401",
      "instrumentalness": "0",
      "liveness": "0.299",
      "valence": "0.701",
      "tempo": "139.567",
      "time_signature": "4",
      "spotify_track_popularity": "53"
    },
    {
      "SongID": "(A Ship Will Come) Ein Schiff Wird KommenLale Anderson",
      "Performer": "Lale Anderson",
      "Song": "(A Ship Will Come) Ein Schiff Wird Kommen",
      "spotify_genre": "[]",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(All I Have To Do Is) DreamThe Nitty Gritty Dirt Band",
      "Performer": "The Nitty Gritty Dirt Band",
      "Song": "(All I Have To Do Is) Dream",
      "spotify_genre": "",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(All Of A Sudden) My Heart SingsMel Carter",
      "Performer": "Mel Carter",
      "Song": "(All Of A Sudden) My Heart Sings",
      "spotify_genre": "[]",
      "spotify_track_id": "6x5BiQwNlbtisITsEHa8Eu",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "164066",
      "spotify_track_explicit": "0",
      "spotify_track_album": "The Best Of Mel Carter",
      "danceability": "0.418",
      "energy": "0.532",
      "key": "7",
      "loudness": "-7.866",
      "mode": "1",
      "speechiness": "0.0354",
      "acousticness": "0.461",
      "instrumentalness": "0.00000299",
      "liveness": "0.83",
      "valence": "0.504",
      "tempo": "117.261",
      "time_signature": "3",
      "spotify_track_popularity": "17"
    },
    {
      "SongID": "(Baby) Hully GullyThe Olympics",
      "Performer": "The Olympics",
      "Song": "(Baby) Hully Gully",
      "spotify_genre": "['doo-wop', 'rhythm and blues']",
      "spotify_track_id": "6UO3m5VERw0IOI0fCXwcvJ",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/2dddf6f576c753c4ddacc93fa2feef6ae073210c?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "127829",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Collectors Gold Series",
      "danceability": "0.744",
      "energy": "0.47",
      "key": "7",
      "loudness": "-10.295",
      "mode": "1",
      "speechiness": "0.035",
      "acousticness": "0.659",
      "instrumentalness": "0",
      "liveness": "0.256",
      "valence": "0.908",
      "tempo": "116.233",
      "time_signature": "4",
      "spotify_track_popularity": "5"
    },
    {
      "SongID": "(Believed You Were) Lucky'Til Tuesday",
      "Performer": "'Til Tuesday",
      "Song": "(Believed You Were) Lucky",
      "spotify_genre": "['boston rock', 'dance rock', 'new romantic', 'new wave', 'new wave pop']",
      "spotify_track_id": "3Lm7hSTabr01oav0WdSsuD",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/9376a6cc89abe5e070e2a056b766d1fb81a98436?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "216973",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Everything's Different Now",
      "danceability": "0.612",
      "energy": "0.523",
      "key": "5",
      "loudness": "-11.425",
      "mode": "1",
      "speechiness": "0.0321",
      "acousticness": "0.448",
      "instrumentalness": "0.00000159",
      "liveness": "0.0727",
      "valence": "0.495",
      "tempo": "124.315",
      "time_signature": "4",
      "spotify_track_popularity": "17"
    },
    {
      "SongID": "(Call Me Your) Anything ManBobby Moore",
      "Performer": "Bobby Moore",
      "Song": "(Call Me Your) Anything Man",
      "spotify_genre": "['classic soul']",
      "spotify_track_id": "0O38BS1klXTO7qRKeEsUK4",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/fae69821573cac51eb16e1591866dc135bd17113?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "374491",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Disco Gold Vol. 2",
      "danceability": "0.624",
      "energy": "0.604",
      "key": "3",
      "loudness": "-12.401",
      "mode": "0",
      "speechiness": "0.0459",
      "acousticness": "0.0474",
      "instrumentalness": "0.00159",
      "liveness": "0.263",
      "valence": "0.76",
      "tempo": "91.554",
      "time_signature": "4",
      "spotify_track_popularity": "4"
    },
    {
      "SongID": "(Closest Thing To) PerfectJermaine Jackson",
      "Performer": "Jermaine Jackson",
      "Song": "(Closest Thing To) Perfect",
      "spotify_genre": "['disco', 'funk', 'post-disco', 'quiet storm', 'urban contemporary']",
      "spotify_track_id": "7pM34Bmj0JY3YNkDOlrcrh",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/07b58bc266ac840c890172ef9341487b3239b91d?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "230693",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Arista Heritage Series: Jermaine Jackson",
      "danceability": "0.661",
      "energy": "0.763",
      "key": "6",
      "loudness": "-12.204",
      "mode": "0",
      "speechiness": "0.0326",
      "acousticness": "0.0205",
      "instrumentalness": "0.000307",
      "liveness": "0.382",
      "valence": "0.905",
      "tempo": "149.974",
      "time_signature": "4",
      "spotify_track_popularity": "8"
    },
    {
      "SongID": "(Dance The) Mess AroundChubby Checker",
      "Performer": "Chubby Checker",
      "Song": "(Dance The) Mess Around",
      "spotify_genre": "['adult standards', 'brill building pop', 'bubblegum pop', 'doo-wop', 'rock-and-roll', 'rockabilly']",
      "spotify_track_id": "1AYJ3jYK65l6wRRk6vJzHM",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/4c5412cf44ba9b8c2ee6df08b9b6a932b594d67e?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "141666",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Chubby Checker Classics",
      "danceability": "0.544",
      "energy": "0.725",
      "key": "1",
      "loudness": "-7.054",
      "mode": "0",
      "speechiness": "0.0759",
      "acousticness": "0.0605",
      "instrumentalness": "0",
      "liveness": "0.112",
      "valence": "0.746",
      "tempo": "141.831",
      "time_signature": "4",
      "spotify_track_popularity": "13"
    },
    {
      "SongID": "(Do You) Wanna RideReel Tight",
      "Performer": "Reel Tight",
      "Song": "(Do You) Wanna Ride",
      "spotify_genre": "[]",
      "spotify_track_id": "7mtYwHLYETUEgA8Sc2Uuxr",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/66be623f9f59ee82b65d32497243628490546513?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "213213",
      "spotify_track_explicit": "0",
      "spotify_track_album": "I Still Know What You Did Last Summer Soundtrack",
      "danceability": "0.757",
      "energy": "0.659",
      "key": "6",
      "loudness": "-5.525",
      "mode": "1",
      "speechiness": "0.0701",
      "acousticness": "0.185",
      "instrumentalness": "0",
      "liveness": "0.0674",
      "valence": "0.878",
      "tempo": "138.045",
      "time_signature": "4",
      "spotify_track_popularity": "7"
    },
    {
      "SongID": "(Don't Fear) The ReaperBlue Oyster Cult",
      "Performer": "Blue Oyster Cult",
      "Song": "(Don't Fear) The Reaper",
      "spotify_genre": "['album rock', 'art rock', 'blues rock', 'classic rock', 'hard rock', 'metal', 'psychedelic rock', 'rock', 'soft rock']",
      "spotify_track_id": "5QTxFnGygVM4jFQiBovmRo",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/596db216a6621b8c0e2f87fb343f33a9c0bd8878?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "308120",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Agents Of Fortune",
      "danceability": "0.333",
      "energy": "0.927",
      "key": "9",
      "loudness": "-8.55",
      "mode": "0",
      "speechiness": "0.0733",
      "acousticness": "0.0029",
      "instrumentalness": "0.000211",
      "liveness": "0.297",
      "valence": "0.382",
      "tempo": "141.47",
      "time_signature": "4",
      "spotify_track_popularity": "77"
    },
    {
      "SongID": "(Don't Worry) If There's A Hell Below We're All Going To GoCurtis Mayfield",
      "Performer": "Curtis Mayfield",
      "Song": "(Don't Worry) If There's A Hell Below We're All Going To Go",
      "spotify_genre": "['chicago soul', 'classic soul', 'disco', 'funk', 'soul']",
      "spotify_track_id": "5RlUTWYlTeE1JiyudvnlAU",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/69225e38740b2674debe0f5d231b1b1ec2cd40e7?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "470506",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Move On Up",
      "danceability": "0.686",
      "energy": "0.755",
      "key": "1",
      "loudness": "-8.304",
      "mode": "0",
      "speechiness": "0.0488",
      "acousticness": "0.149",
      "instrumentalness": "0.063",
      "liveness": "0.111",
      "valence": "0.686",
      "tempo": "119.895",
      "time_signature": "4",
      "spotify_track_popularity": "15"
    },
    {
      "SongID": "(everybody Wanna Get Rich) Rite AwayDr. John",
      "Performer": "Dr. John",
      "Song": "(everybody Wanna Get Rich) Rite Away",
      "spotify_genre": "['blues', 'blues rock', 'classic rock', 'electric blues', 'folk rock', 'funk', 'jazz blues', 'louisiana blues', 'new orleans blues', 'piano blues', 'psychedelic rock', 'roots rock', 'soul']",
      "spotify_track_id": "2a0fkN8dbA5Kh8SR7cvl3D",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/94ed76522a63c1b269bdf30b94f05d993e833aaf?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "163933",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Destively Bonnaroo",
      "danceability": "0.746",
      "energy": "0.916",
      "key": "9",
      "loudness": "-10.061",
      "mode": "1",
      "speechiness": "0.0772",
      "acousticness": "0.518",
      "instrumentalness": "0.0686",
      "liveness": "0.0785",
      "valence": "0.971",
      "tempo": "99.926",
      "time_signature": "4",
      "spotify_track_popularity": "54"
    },
    {
      "SongID": "(For God's Sake) Give More Power To The PeopleThe Chi-lites",
      "Performer": "The Chi-lites",
      "Song": "(For God's Sake) Give More Power To The People",
      "spotify_genre": "['chicago soul', 'classic soul', 'disco', 'funk', 'motown', 'quiet storm', 'soul', 'southern soul']",
      "spotify_track_id": "0dVabf3Sm1uHODq1vz2Lts",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/e6d56add4e9409e78f087a02053a013c05af8c38?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "180133",
      "spotify_track_explicit": "0",
      "spotify_track_album": "The Ultimate Chi-Lites",
      "danceability": "0.665",
      "energy": "0.552",
      "key": "6",
      "loudness": "-10.177",
      "mode": "1",
      "speechiness": "0.0307",
      "acousticness": "0.493",
      "instrumentalness": "0.0272",
      "liveness": "0.421",
      "valence": "0.899",
      "tempo": "96.889",
      "time_signature": "4",
      "spotify_track_popularity": "29"
    },
    {
      "SongID": "(Ghost) Riders In The SkyOutlaws",
      "Performer": "Outlaws",
      "Song": "(Ghost) Riders In The Sky",
      "spotify_genre": "['album rock', 'blues rock', 'classic rock', 'country rock', 'hard rock', 'mellow gold', 'rock', 'soft rock', 'southern rock']",
      "spotify_track_id": "4ncVYIs3UFvitjvc8RIPkM",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/be20c6462522bcb1b8587f222a83dba32b94fd76?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "351400",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Ghost Riders",
      "danceability": "0.228",
      "energy": "0.896",
      "key": "9",
      "loudness": "-7.241",
      "mode": "0",
      "speechiness": "0.13",
      "acousticness": "0.0132",
      "instrumentalness": "0.0273",
      "liveness": "0.795",
      "valence": "0.146",
      "tempo": "128.433",
      "time_signature": "4",
      "spotify_track_popularity": "47"
    },
    {
      "SongID": "(Ghost) Riders In The SkyRamrods",
      "Performer": "Ramrods",
      "Song": "(Ghost) Riders In The Sky",
      "spotify_genre": "['classic garage rock']",
      "spotify_track_id": "5eUVr9Ja4GK6e1lcIXjML7",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/19307e9a712d0793f222261d891c1b741888124e?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "156933",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Ghost Riders in the Sky",
      "danceability": "0.442",
      "energy": "0.717",
      "key": "9",
      "loudness": "-9.943",
      "mode": "0",
      "speechiness": "0.0395",
      "acousticness": "0.518",
      "instrumentalness": "0.262",
      "liveness": "0.184",
      "valence": "0.376",
      "tempo": "120.914",
      "time_signature": "4",
      "spotify_track_popularity": "24"
    },
    {
      "SongID": "(Girls, Girls, Girls) Made To LoveEddie Hodges",
      "Performer": "Eddie Hodges",
      "Song": "(Girls, Girls, Girls) Made To Love",
      "spotify_genre": "[]",
      "spotify_track_id": "4PeZdZt3Mf46SfsL6Gj1EY",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/6d5a4642f5e2503d56c7b45c22a82adf56737020?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "150666",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Hit Singles - EP",
      "danceability": "0.61",
      "energy": "0.377",
      "key": "9",
      "loudness": "-9.805",
      "mode": "1",
      "speechiness": "0.0935",
      "acousticness": "0.414",
      "instrumentalness": "0",
      "liveness": "0.0734",
      "valence": "0.519",
      "tempo": "178.06",
      "time_signature": "4",
      "spotify_track_popularity": "16"
    },
    {
      "SongID": "(God Must Have Spent) A Little More Time On You'N Sync",
      "Performer": "'N Sync",
      "Song": "(God Must Have Spent) A Little More Time On You",
      "spotify_genre": "[]",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(He's) The Great ImpostorThe Fleetwoods",
      "Performer": "The Fleetwoods",
      "Song": "(He's) The Great Impostor",
      "spotify_genre": "['adult standards', 'brill building pop', 'doo-wop', 'rhythm and blues', 'rock-and-roll', 'vocal harmony group']",
      "spotify_track_id": "2NBfPm9rWk2nYVDengT80Z",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/aad77e322af047f2644169ec946930187f58e0d9?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "132101",
      "spotify_track_explicit": "0",
      "spotify_track_album": "The Fleetwoods Greatest Hits",
      "danceability": "0.499",
      "energy": "0.249",
      "key": "5",
      "loudness": "-11.793",
      "mode": "1",
      "speechiness": "0.0422",
      "acousticness": "0.733",
      "instrumentalness": "0",
      "liveness": "0.105",
      "valence": "0.539",
      "tempo": "117.163",
      "time_signature": "4",
      "spotify_track_popularity": "15"
    },
    {
      "SongID": "(Here They Come) From All Over The WorldJan & Dean",
      "Performer": "Jan & Dean",
      "Song": "(Here They Come) From All Over The World",
      "spotify_genre": "['christmas instrumental']",
      "spotify_track_id": "5TrvERHRtiRshORTehfs0w",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "164600",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Surf City: The Best Of Jan & Dean",
      "danceability": "0.461",
      "energy": "0.68",
      "key": "0",
      "loudness": "-10.699",
      "mode": "1",
      "speechiness": "0.0446",
      "acousticness": "0.621",
      "instrumentalness": "0.00000774",
      "liveness": "0.906",
      "valence": "0.957",
      "tempo": "149.771",
      "time_signature": "4",
      "spotify_track_popularity": "15"
    },
    {
      "SongID": "(Hey Won't You Play) Another Somebody Done Somebody Wrong SongB.J. Thomas",
      "Performer": "B.J. Thomas",
      "Song": "(Hey Won't You Play) Another Somebody Done Somebody Wrong Song",
      "spotify_genre": "['adult standards', 'brill building pop', 'bubblegum pop', 'classic country pop', 'country rock', 'folk', 'folk rock', 'mellow gold', 'soft rock']",
      "spotify_track_id": "0b7qiL1rLbUUpGXczt7p5T",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "206066",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Reunion",
      "danceability": "0.637",
      "energy": "0.528",
      "key": "4",
      "loudness": "-11.287",
      "mode": "1",
      "speechiness": "0.0328",
      "acousticness": "0.744",
      "instrumentalness": "0",
      "liveness": "0.114",
      "valence": "0.702",
      "tempo": "124.806",
      "time_signature": "4",
      "spotify_track_popularity": "40"
    },
    {
      "SongID": "(Hot S**t) Country GrammarNelly",
      "Performer": "Nelly",
      "Song": "(Hot S**t) Country Grammar",
      "spotify_genre": "['dance pop', 'hip hop', 'pop', 'pop rap', 'rap', 'southern hip hop', 'urban contemporary']",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(How Bout A Little Hand For) The Boys In The BandThe Boys In The Band",
      "Performer": "The Boys In The Band",
      "Song": "(How Bout A Little Hand For) The Boys In The Band",
      "spotify_genre": "[]",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(How Can I Write On Paper) What I Feel In My HeartJim Reeves",
      "Performer": "Jim Reeves",
      "Song": "(How Can I Write On Paper) What I Feel In My Heart",
      "spotify_genre": "['adult standards', 'nashville sound', 'rock-and-roll']",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(How I Spent My Summer Vacation) Or A Day At The Beach With Pedro & Man - PCheech & Chong",
      "Performer": "Cheech & Chong",
      "Song": "(How I Spent My Summer Vacation) Or A Day At The Beach With Pedro & Man - P",
      "spotify_genre": "[]",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(How To Be A) MillionaireABC",
      "Performer": "ABC",
      "Song": "(How To Be A) Millionaire",
      "spotify_genre": "[]",
      "spotify_track_id": "3zC02nmo5OrDDMW3U905AU",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "215733",
      "spotify_track_explicit": "0",
      "spotify_track_album": "How To Be A Zillionaire",
      "danceability": "0.718",
      "energy": "0.755",
      "key": "2",
      "loudness": "-9.683",
      "mode": "1",
      "speechiness": "0.0534",
      "acousticness": "0.281",
      "instrumentalness": "0.0000118",
      "liveness": "0.0614",
      "valence": "0.832",
      "tempo": "121.678",
      "time_signature": "4",
      "spotify_track_popularity": "29"
    },
    {
      "SongID": "(I Believe) There's Nothing Stronger Than Our LovePaul Anka/Odia Coates",
      "Performer": "Paul Anka/Odia Coates",
      "Song": "(I Believe) There's Nothing Stronger Than Our Love",
      "spotify_genre": "",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(I Can Feel Those Vibrations) This Love Is RealJackie Wilson",
      "Performer": "Jackie Wilson",
      "Song": "(I Can Feel Those Vibrations) This Love Is Real",
      "spotify_genre": "['adult standards', 'brill building pop', 'chicago soul', 'classic soul', 'motown', 'quiet storm', 'rhythm and blues', 'rock-and-roll', 'rockabilly', 'soul']",
      "spotify_track_id": "2QM3bCcmAwiuwDvhIispV8",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/341d37a9332998e830abfbcdb46bf65a6dd8139c?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "175146",
      "spotify_track_explicit": "0",
      "spotify_track_album": "The Ultimate Jackie Wilson",
      "danceability": "0.63",
      "energy": "0.8",
      "key": "2",
      "loudness": "-6.002",
      "mode": "1",
      "speechiness": "0.15",
      "acousticness": "0.429",
      "instrumentalness": "0",
      "liveness": "0.3",
      "valence": "0.736",
      "tempo": "120.811",
      "time_signature": "4",
      "spotify_track_popularity": "26"
    },
    {
      "SongID": "(I Can Feel Your Love) Slipping AwayBarbara Mason",
      "Performer": "Barbara Mason",
      "Song": "(I Can Feel Your Love) Slipping Away",
      "spotify_genre": "['classic soul', 'funk', 'motown', 'philly soul', 'quiet storm', 'southern soul']",
      "spotify_track_id": "37kJMIJyTv96Tns8QgsOJn",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/0692f0732a4bf399249151bcc57edd0d62138b5b?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "199626",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Cooler Than Ice: Arctic Records and the Rise of Philly Soul",
      "danceability": "0.44",
      "energy": "0.427",
      "key": "0",
      "loudness": "-5.455",
      "mode": "1",
      "speechiness": "0.0254",
      "acousticness": "0.563",
      "instrumentalness": "0",
      "liveness": "0.295",
      "valence": "0.335",
      "tempo": "77.412",
      "time_signature": "3",
      "spotify_track_popularity": "16"
    },
    {
      "SongID": "(I Can't Get No) SatisfactionThe Rolling Stones",
      "Performer": "The Rolling Stones",
      "Song": "(I Can't Get No) Satisfaction",
      "spotify_genre": "['album rock', 'british invasion', 'classic rock', 'protopunk', 'rock']",
      "spotify_track_id": "2PzU4IB8Dr6mxV3lHuaG34",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "222813",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Out Of Our Heads",
      "danceability": "0.725",
      "energy": "0.853",
      "key": "2",
      "loudness": "-7.842",
      "mode": "1",
      "speechiness": "0.0353",
      "acousticness": "0.0348",
      "instrumentalness": "0.127",
      "liveness": "0.196",
      "valence": "0.904",
      "tempo": "136.282",
      "time_signature": "4",
      "spotify_track_popularity": "78"
    },
    {
      "SongID": "(I Can't Help You) I'm Falling TooSkeeter Davis",
      "Performer": "Skeeter Davis",
      "Song": "(I Can't Help You) I'm Falling Too",
      "spotify_genre": "['brill building pop', 'nashville sound']",
      "spotify_track_id": "5MXe6dKcR6iO33GWzVW8cr",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/c116a9c6b95d4b6384d9320685e84388b9ac6364?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "165266",
      "spotify_track_explicit": "0",
      "spotify_track_album": "The Essential Skeeter Davis",
      "danceability": "0.617",
      "energy": "0.197",
      "key": "9",
      "loudness": "-12.145",
      "mode": "1",
      "speechiness": "0.0267",
      "acousticness": "0.777",
      "instrumentalness": "0",
      "liveness": "0.133",
      "valence": "0.384",
      "tempo": "91.209",
      "time_signature": "4",
      "spotify_track_popularity": "23"
    },
    {
      "SongID": "(I Could Only) Whisper Your NameHarry Connick, Jr.",
      "Performer": "Harry Connick, Jr.",
      "Song": "(I Could Only) Whisper Your Name",
      "spotify_genre": "['adult standards', 'contemporary vocal jazz', 'lounge', 'vocal jazz']",
      "spotify_track_id": "68EKUNtzGVapUS30PJDVKs",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/fe4b109b248e6c714e37278ee5039ddfc66bc83b?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "289970",
      "spotify_track_explicit": "0",
      "spotify_track_album": "She",
      "danceability": "0.682",
      "energy": "0.572",
      "key": "5",
      "loudness": "-7.067",
      "mode": "0",
      "speechiness": "0.045",
      "acousticness": "0.191",
      "instrumentalness": "0.204",
      "liveness": "0.0504",
      "valence": "0.844",
      "tempo": "89.083",
      "time_signature": "4",
      "spotify_track_popularity": "34"
    },
    {
      "SongID": "(I Cried at) Laura's WeddingBarbara Lynn",
      "Performer": "Barbara Lynn",
      "Song": "(I Cried at) Laura's Wedding",
      "spotify_genre": "['classic soul', 'motown', 'rhythm and blues', 'soul', 'southern soul']",
      "spotify_track_id": "1kWnbqS0pNBX9UNFIdBoXw",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/31d79bfd866c910c4fe0b619e0e0ee8f5d8c3622?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "158213",
      "spotify_track_explicit": "0",
      "spotify_track_album": "The Jamie Singles Collection 1962-1965",
      "danceability": "0.579",
      "energy": "0.299",
      "key": "7",
      "loudness": "-8.729",
      "mode": "1",
      "speechiness": "0.0304",
      "acousticness": "0.84",
      "instrumentalness": "0.0000471",
      "liveness": "0.117",
      "valence": "0.194",
      "tempo": "89.463",
      "time_signature": "3",
      "spotify_track_popularity": "2"
    },
    {
      "SongID": "(I Do The) Shimmy ShimmyBobby Freeman",
      "Performer": "Bobby Freeman",
      "Song": "(I Do The) Shimmy Shimmy",
      "spotify_genre": "['doo-wop', 'rhythm and blues', 'rock-and-roll', 'rockabilly']",
      "spotify_track_id": "2FQcPtw6VJ8t2D8YC6OiCC",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/835a6d254c287a4af69dcb1e6dda0c9db5f70791?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "157466",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Greatest Hits",
      "danceability": "0.508",
      "energy": "0.857",
      "key": "2",
      "loudness": "-5.498",
      "mode": "1",
      "speechiness": "0.04",
      "acousticness": "0.74",
      "instrumentalness": "0",
      "liveness": "0.365",
      "valence": "0.891",
      "tempo": "88.579",
      "time_signature": "4",
      "spotify_track_popularity": "3"
    },
    {
      "SongID": "(I Don't Care) Only Love MeSteve Lawrence",
      "Performer": "Steve Lawrence",
      "Song": "(I Don't Care) Only Love Me",
      "spotify_genre": "['adult standards', 'brill building pop', 'deep adult standards', 'easy listening', 'lounge', 'vocal jazz']",
      "spotify_track_id": "2tve82MQkxXX1WsdxpI4sk",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "153600",
      "spotify_track_explicit": "0",
      "spotify_track_album": "The Best Of",
      "danceability": "0.56",
      "energy": "0.516",
      "key": "5",
      "loudness": "-12.275",
      "mode": "0",
      "speechiness": "0.183",
      "acousticness": "0.468",
      "instrumentalness": "0.000107",
      "liveness": "0.173",
      "valence": "0.825",
      "tempo": "141.812",
      "time_signature": "4",
      "spotify_track_popularity": "13"
    },
    {
      "SongID": "(I Don't Want To Love You But) You Got Me AnywaySutherland Brothers And Quiver",
      "Performer": "Sutherland Brothers And Quiver",
      "Song": "(I Don't Want To Love You But) You Got Me Anyway",
      "spotify_genre": "['classic uk pop']",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(I Hate) Everything About YouThree Days Grace",
      "Performer": "Three Days Grace",
      "Song": "(I Hate) Everything About You",
      "spotify_genre": "['alternative metal', 'canadian metal', 'canadian rock', 'nu metal', 'post-grunge']",
      "spotify_track_id": "6rUp7v3l8yC4TKxAAR5Bmx",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/8893669447625edf76339cdd67a338dad034a7ea?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "231480",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Three Days Grace (Deluxe Version)",
      "danceability": "0.498",
      "energy": "0.83",
      "key": "6",
      "loudness": "-5.157",
      "mode": "0",
      "speechiness": "0.0421",
      "acousticness": "0.00461",
      "instrumentalness": "0",
      "liveness": "0.139",
      "valence": "0.453",
      "tempo": "89.342",
      "time_signature": "4",
      "spotify_track_popularity": "74"
    },
    {
      "SongID": "(I Just) Died In Your ArmsCutting Crew",
      "Performer": "Cutting Crew",
      "Song": "(I Just) Died In Your Arms",
      "spotify_genre": "['album rock', 'dance rock', 'mellow gold', 'new romantic', 'new wave', 'new wave pop', 'soft rock', 'synthpop']",
      "spotify_track_id": "0YPXkQthLWrhNGoKTbwCJ8",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "278626",
      "spotify_track_explicit": "0",
      "spotify_track_album": "The Best Of Cutting Crew",
      "danceability": "0.632",
      "energy": "0.727",
      "key": "11",
      "loudness": "-11.209",
      "mode": "0",
      "speechiness": "0.0438",
      "acousticness": "0.0119",
      "instrumentalness": "0.0000764",
      "liveness": "0.0678",
      "valence": "0.499",
      "tempo": "124.919",
      "time_signature": "4",
      "spotify_track_popularity": "70"
    },
    {
      "SongID": "(I Know I Got) SkillzShaquille O'Neal",
      "Performer": "Shaquille O'Neal",
      "Song": "(I Know I Got) Skillz",
      "spotify_genre": "['new jersey rap']",
      "spotify_track_id": "0TEQ2QmFXnHCgQvYuvsbp2",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/6a164d9db727f8583342cbd3d7b125b66e9e5332?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "263053",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Shaq Diesel",
      "danceability": "0.801",
      "energy": "0.875",
      "key": "7",
      "loudness": "-9.705",
      "mode": "1",
      "speechiness": "0.0995",
      "acousticness": "0.00366",
      "instrumentalness": "0.425",
      "liveness": "0.182",
      "valence": "0.637",
      "tempo": "91.983",
      "time_signature": "4",
      "spotify_track_popularity": "33"
    },
    {
      "SongID": "(I Know) I'm Losing YouRare Earth",
      "Performer": "Rare Earth",
      "Song": "(I Know) I'm Losing You",
      "spotify_genre": "['blues rock', 'classic rock', 'motown']",
      "spotify_track_id": "18bZGZU0wZ2lV1SEDoXqqr",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "215986",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Ecology",
      "danceability": "0.38",
      "energy": "0.532",
      "key": "6",
      "loudness": "-14.477",
      "mode": "1",
      "speechiness": "0.0434",
      "acousticness": "0.537",
      "instrumentalness": "0.0000462",
      "liveness": "0.321",
      "valence": "0.79",
      "tempo": "99.865",
      "time_signature": "4",
      "spotify_track_popularity": "32"
    },
    {
      "SongID": "(I Know) I'm Losing YouRod Stewart With Faces",
      "Performer": "Rod Stewart With Faces",
      "Song": "(I Know) I'm Losing You",
      "spotify_genre": "",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(I Know) I'm Losing YouThe Temptations",
      "Performer": "The Temptations",
      "Song": "(I Know) I'm Losing You",
      "spotify_genre": "['adult standards', 'brill building pop', 'classic soul', 'funk', 'memphis soul', 'motown', 'soul']",
      "spotify_track_id": "6y8o4V2R2dSt2ijgL8C72W",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "149493",
      "spotify_track_explicit": "0",
      "spotify_track_album": "With A Lot O' Soul",
      "danceability": "0.634",
      "energy": "0.503",
      "key": "5",
      "loudness": "-11.89",
      "mode": "1",
      "speechiness": "0.0282",
      "acousticness": "0.5",
      "instrumentalness": "0",
      "liveness": "0.0465",
      "valence": "0.813",
      "tempo": "109.57",
      "time_signature": "4",
      "spotify_track_popularity": "44"
    },
    {
      "SongID": "(I Know) I'm Losing YouUptown",
      "Performer": "Uptown",
      "Song": "(I Know) I'm Losing You",
      "spotify_genre": "[]",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(I Love You) Don't You Forget ItPerry Como",
      "Performer": "Perry Como",
      "Song": "(I Love You) Don't You Forget It",
      "spotify_genre": "['adult standards', 'brill building pop', 'easy listening', 'vocal jazz']",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(I Never Promised You A) Rose GardenMartina McBride",
      "Performer": "Martina McBride",
      "Song": "(I Never Promised You A) Rose Garden",
      "spotify_genre": "['contemporary country', 'country', 'country dawn', 'country road']",
      "spotify_track_id": "6goA1BGYQSSricr7oV8r8m",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/65d5137fd83ff2c10c628502147570042302d06a?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "195573",
      "spotify_track_explicit": "0",
      "spotify_track_album": "The Essential Martina McBride",
      "danceability": "0.577",
      "energy": "0.728",
      "key": "2",
      "loudness": "-6.944",
      "mode": "1",
      "speechiness": "0.0478",
      "acousticness": "0.503",
      "instrumentalness": "0",
      "liveness": "0.133",
      "valence": "0.78",
      "tempo": "131.908",
      "time_signature": "4",
      "spotify_track_popularity": "30"
    },
    {
      "SongID": "(I Remember) Summer MorningVanity Fare",
      "Performer": "Vanity Fare",
      "Song": "(I Remember) Summer Morning",
      "spotify_genre": "['bubblegum pop', 'classic uk pop', 'merseybeat']",
      "spotify_track_id": "5iDkKAJZxGaqIo4Z32ZbjD",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/10809612f825fcf98d914d9cda3485edb226d95f?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "178418",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Early in the Morning",
      "danceability": "0.528",
      "energy": "0.341",
      "key": "4",
      "loudness": "-12.768",
      "mode": "0",
      "speechiness": "0.03",
      "acousticness": "0.922",
      "instrumentalness": "0",
      "liveness": "0.135",
      "valence": "0.337",
      "tempo": "111.336",
      "time_signature": "4",
      "spotify_track_popularity": "3"
    },
    {
      "SongID": "(I Wanna) Dance With The TeacherThe Olympics",
      "Performer": "The Olympics",
      "Song": "(I Wanna) Dance With The Teacher",
      "spotify_genre": "['doo-wop', 'rhythm and blues']",
      "spotify_track_id": "3rHQ8LI3Rrw2hy7H4FtbFw",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/d6e33d7dfe1f63f3458d0eb4e71285ed2fea2ce3?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "107317",
      "spotify_track_explicit": "0",
      "spotify_track_album": "The Very Best of the Olympics",
      "danceability": "0.567",
      "energy": "0.458",
      "key": "4",
      "loudness": "-15.353",
      "mode": "1",
      "speechiness": "0.0623",
      "acousticness": "0.428",
      "instrumentalness": "0.0412",
      "liveness": "0.356",
      "valence": "0.829",
      "tempo": "85.189",
      "time_signature": "4",
      "spotify_track_popularity": "1"
    },
    {
      "SongID": "(I Wanna) Love My Life AwayGene Pitney",
      "Performer": "Gene Pitney",
      "Song": "(I Wanna) Love My Life Away",
      "spotify_genre": "['adult standards', 'brill building pop', 'bubblegum pop', 'classic uk pop', 'folk rock', 'merseybeat', 'rock-and-roll']",
      "spotify_track_id": "1fNR9tY52D1V79V5eNqxxx",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/5be4e9acd6d2bf25525372ae5811c06a7f5789a2?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "114906",
      "spotify_track_explicit": "0",
      "spotify_track_album": "The Best Of Gene Pitney",
      "danceability": "0.548",
      "energy": "0.694",
      "key": "0",
      "loudness": "-9.356",
      "mode": "1",
      "speechiness": "0.0359",
      "acousticness": "0.811",
      "instrumentalness": "0.0000538",
      "liveness": "0.596",
      "valence": "0.924",
      "tempo": "136.36",
      "time_signature": "4",
      "spotify_track_popularity": "26"
    },
    {
      "SongID": "(I Wanna) TestifyThe Parliaments",
      "Performer": "The Parliaments",
      "Song": "(I Wanna) Testify",
      "spotify_genre": "[]",
      "spotify_track_id": "0xAqhyWvTkfcdFgm7dozMO",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/ba2d79fa2c43227fb4ba82b005dec1cfd4bf87d8?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "183693",
      "spotify_track_explicit": "0",
      "spotify_track_album": "So Fine: '60s One Hit Wonders",
      "danceability": "0.668",
      "energy": "0.702",
      "key": "10",
      "loudness": "-5.75",
      "mode": "1",
      "speechiness": "0.033",
      "acousticness": "0.336",
      "instrumentalness": "0",
      "liveness": "0.0521",
      "valence": "0.754",
      "tempo": "105.227",
      "time_signature": "4",
      "spotify_track_popularity": "16"
    },
    {
      "SongID": "(I was) Born To CryDion",
      "Performer": "Dion",
      "Song": "(I was) Born To Cry",
      "spotify_genre": "['canadian pop', 'dance pop']",
      "spotify_track_id": "5P6O4yi0sZ4JUOJAlmZvxM",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "147560",
      "spotify_track_explicit": "0",
      "spotify_track_album": "The Best Of Dion & The Belmonts",
      "danceability": "0.396",
      "energy": "0.568",
      "key": "7",
      "loudness": "-11.25",
      "mode": "0",
      "speechiness": "0.0639",
      "acousticness": "0.322",
      "instrumentalness": "0",
      "liveness": "0.181",
      "valence": "0.607",
      "tempo": "119.676",
      "time_signature": "4",
      "spotify_track_popularity": "28"
    },
    {
      "SongID": "(I Washed My Hands In) Muddy WaterJohnny Rivers",
      "Performer": "Johnny Rivers",
      "Song": "(I Washed My Hands In) Muddy Water",
      "spotify_genre": "['brill building pop', 'bubblegum pop', 'folk rock', 'mellow gold', 'rock-and-roll', 'soft rock']",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(I Will Be Your) Shadow In The StreetAllan Clarke",
      "Performer": "Allan Clarke",
      "Song": "(I Will Be Your) Shadow In The Street",
      "spotify_genre": "[]",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(I'd Know You) AnywhereAshford & Simpson",
      "Performer": "Ashford & Simpson",
      "Song": "(I'd Know You) Anywhere",
      "spotify_genre": "['broadway', 'hollywood', 'show tunes']",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(I'll Be With You In) Apple Blossom TimeTab Hunter",
      "Performer": "Tab Hunter",
      "Song": "(I'll Be With You In) Apple Blossom Time",
      "spotify_genre": "['deep adult standards']",
      "spotify_track_id": "7p4NwdRBX4tbBaQBRZXnTM",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/53a0d13997c23738b4ffaa1e5e47f7a7b0115f20?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "130759",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Your Pop - Tastic! Collectio",
      "danceability": "0.585",
      "energy": "0.45",
      "key": "8",
      "loudness": "-9.468",
      "mode": "1",
      "speechiness": "0.0357",
      "acousticness": "0.856",
      "instrumentalness": "0.00000492",
      "liveness": "0.0777",
      "valence": "0.627",
      "tempo": "130.16",
      "time_signature": "4",
      "spotify_track_popularity": "8"
    },
    {
      "SongID": "(I'm A) Road RunnerJr. Walker & The All Stars",
      "Performer": "Jr. Walker & The All Stars",
      "Song": "(I'm A) Road Runner",
      "spotify_genre": "['outlaw country', 'redneck']",
      "spotify_track_id": "5llZqDjRHnn5pAUswFqQCf",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "165946",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Shotgun",
      "danceability": "0.755",
      "energy": "0.695",
      "key": "5",
      "loudness": "-6.56",
      "mode": "1",
      "speechiness": "0.0281",
      "acousticness": "0.0533",
      "instrumentalness": "0",
      "liveness": "0.295",
      "valence": "0.851",
      "tempo": "125.256",
      "time_signature": "4",
      "spotify_track_popularity": "48"
    },
    {
      "SongID": "(I'm A) YoYo ManRick Cunha",
      "Performer": "Rick Cunha",
      "Song": "(I'm A) YoYo Man",
      "spotify_genre": "[]",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(I'm Going By) The Stars In Your EyesRon Banks And The Dramatics",
      "Performer": "Ron Banks And The Dramatics",
      "Song": "(I'm Going By) The Stars In Your Eyes",
      "spotify_genre": "",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(I'm Just A) Fool For YouGene Chandler",
      "Performer": "Gene Chandler",
      "Song": "(I'm Just A) Fool For You",
      "spotify_genre": "['brill building pop', 'chicago soul', 'classic soul', 'doo-wop', 'motown', 'northern soul', 'rhythm and blues', 'soul', 'southern soul']",
      "spotify_track_id": "0FESeUvkf85Xj65Yv08Ovf",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/3d981e7011684b95bdf45714180e40b2bf04293e?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "160853",
      "spotify_track_explicit": "0",
      "spotify_track_album": "The Girl Don't Care",
      "danceability": "0.564",
      "energy": "0.623",
      "key": "2",
      "loudness": "-9.553",
      "mode": "1",
      "speechiness": "0.0319",
      "acousticness": "0.288",
      "instrumentalness": "0.0000131",
      "liveness": "0.0947",
      "valence": "0.911",
      "tempo": "110.613",
      "time_signature": "4",
      "spotify_track_popularity": "8"
    },
    {
      "SongID": "(I'm Not Your) Steppin' StoneThe Monkees",
      "Performer": "The Monkees",
      "Song": "(I'm Not Your) Steppin' Stone",
      "spotify_genre": "['brill building pop', 'bubblegum pop', 'classic rock', 'folk', 'folk rock', 'mellow gold', 'psychedelic rock', 'rock', 'rock-and-roll', 'soft rock', 'sunshine pop']",
      "spotify_track_id": "7dvtNWoHd3ioEBmIl0s3In",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/43d579d5bcc7d92a53c7b4b9146a5d2c645f9d30?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "146533",
      "spotify_track_explicit": "0",
      "spotify_track_album": "More of The Monkees (Deluxe Edition)",
      "danceability": "0.537",
      "energy": "0.677",
      "key": "5",
      "loudness": "-4.437",
      "mode": "1",
      "speechiness": "0.0301",
      "acousticness": "0.0151",
      "instrumentalness": "0.000199",
      "liveness": "0.0981",
      "valence": "0.324",
      "tempo": "131.477",
      "time_signature": "4",
      "spotify_track_popularity": "45"
    },
    {
      "SongID": "(I'm So) Afraid Of Losing You AgainCharley Pride",
      "Performer": "Charley Pride",
      "Song": "(I'm So) Afraid Of Losing You Again",
      "spotify_genre": "['classic country pop', 'country', 'country rock', 'nashville sound']",
      "spotify_track_id": "5drsRsgpbfvKGlhMcb5hKt",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/26fabb75f960a3e8ae44bfc7903f651cf063cadc?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "173320",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Greatest Hits Collection",
      "danceability": "0.525",
      "energy": "0.354",
      "key": "4",
      "loudness": "-12.332",
      "mode": "1",
      "speechiness": "0.0344",
      "acousticness": "0.466",
      "instrumentalness": "0.0000386",
      "liveness": "0.246",
      "valence": "0.495",
      "tempo": "109.498",
      "time_signature": "4",
      "spotify_track_popularity": "30"
    },
    {
      "SongID": "(I'm Watching) Every Little Move You MakeLittle Peggy March",
      "Performer": "Little Peggy March",
      "Song": "(I'm Watching) Every Little Move You Make",
      "spotify_genre": "['brill building pop']",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(i've Been) Searchin' So LongChicago",
      "Performer": "Chicago",
      "Song": "(i've Been) Searchin' So Long",
      "spotify_genre": "['adult standards', 'album rock', 'classic rock', 'folk rock', 'mellow gold', 'rock', 'soft rock', 'yacht rock']",
      "spotify_track_id": "3z9pBucv2HHp1gYaTcQwiI",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/4380998b256a31e82ce8ac356476655a14fa1151?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "268426",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Chicago VII (Expanded & Remastered)",
      "danceability": "0.194",
      "energy": "0.591",
      "key": "0",
      "loudness": "-6.181",
      "mode": "1",
      "speechiness": "0.0318",
      "acousticness": "0.118",
      "instrumentalness": "0.0000643",
      "liveness": "0.2",
      "valence": "0.164",
      "tempo": "171.066",
      "time_signature": "4",
      "spotify_track_popularity": "41"
    },
    {
      "SongID": "(I've Got) BonnieBobby Rydell",
      "Performer": "Bobby Rydell",
      "Song": "(I've Got) Bonnie",
      "spotify_genre": "['adult standards', 'brill building pop', 'bubblegum pop', 'deep adult standards', 'doo-wop', 'merseybeat', 'rock-and-roll', 'rockabilly']",
      "spotify_track_id": "5XbZjYB4z9OIJhutiDJeSV",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "147000",
      "spotify_track_explicit": "0",
      "spotify_track_album": "The Best Of Bobby Rydell",
      "danceability": "0.329",
      "energy": "0.398",
      "key": "2",
      "loudness": "-7.385",
      "mode": "1",
      "speechiness": "0.0286",
      "acousticness": "0.77",
      "instrumentalness": "0",
      "liveness": "0.242",
      "valence": "0.698",
      "tempo": "75.194",
      "time_signature": "4",
      "spotify_track_popularity": "10"
    },
    {
      "SongID": "(I've Got) Spring FeverLittle Willie John",
      "Performer": "Little Willie John",
      "Song": "(I've Got) Spring Fever",
      "spotify_genre": "['rhythm and blues', 'rock-and-roll', 'soul', 'southern soul']",
      "spotify_track_id": "2QgRceE7yUSn82yLDAA3ZS",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/1abfac68ff69a358974ece3f993716a3f4ad0c5c?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "131533",
      "spotify_track_explicit": "0",
      "spotify_track_album": "28 Big Ones",
      "danceability": "0.699",
      "energy": "0.373",
      "key": "0",
      "loudness": "-12.653",
      "mode": "1",
      "speechiness": "0.0813",
      "acousticness": "0.801",
      "instrumentalness": "0.518",
      "liveness": "0.0764",
      "valence": "0.73",
      "tempo": "134.923",
      "time_signature": "4",
      "spotify_track_popularity": "2"
    },
    {
      "SongID": "(I've Had) The Time Of My LifeBill Medley & Jennifer Warnes",
      "Performer": "Bill Medley & Jennifer Warnes",
      "Song": "(I've Had) The Time Of My Life",
      "spotify_genre": "['soft rock']",
      "spotify_track_id": "4BFMQ15vXr626UOoZL8bUI",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/a8fb0eb28d9d8f6ca56252a18ba84ecbe434a294?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "289066",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Platinum & Gold Collection",
      "danceability": "0.7",
      "energy": "0.781",
      "key": "6",
      "loudness": "-8.255",
      "mode": "0",
      "speechiness": "0.0507",
      "acousticness": "0.0874",
      "instrumentalness": "0.00342",
      "liveness": "0.059",
      "valence": "0.385",
      "tempo": "108.695",
      "time_signature": "4",
      "spotify_track_popularity": "70"
    },
    {
      "SongID": "(I've Had) The Time Of My LifeGlee Cast",
      "Performer": "Glee Cast",
      "Song": "(I've Had) The Time Of My Life",
      "spotify_genre": "['glee club', 'hollywood', 'post-teen pop']",
      "spotify_track_id": "1wYDz3NuqlGxPnQDX8OuV6",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/160f06753d3555c8699ed1d9165de2c79c076023?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "277560",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Glee: The Musi",
      "danceability": "0.459",
      "energy": "0.77",
      "key": "9",
      "loudness": "-5.996",
      "mode": "1",
      "speechiness": "0.0472",
      "acousticness": "0.0765",
      "instrumentalness": "0",
      "liveness": "0.0879",
      "valence": "0.168",
      "tempo": "110.705",
      "time_signature": "4",
      "spotify_track_popularity": "49"
    },
    {
      "SongID": "(If Loving You Is Wrong) I Don't Want To Be RightBarbara Mandrell",
      "Performer": "Barbara Mandrell",
      "Song": "(If Loving You Is Wrong) I Don't Want To Be Right",
      "spotify_genre": "['classic country pop', 'country', 'country gospel', 'country rock']",
      "spotify_track_id": "1cxjGdsHJn2vo17AbWLFzu",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "185013",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Ultimate Collection: Barbara Mandrell",
      "danceability": "0.628",
      "energy": "0.536",
      "key": "4",
      "loudness": "-10.905",
      "mode": "0",
      "speechiness": "0.0324",
      "acousticness": "0.038",
      "instrumentalness": "0.0000123",
      "liveness": "0.115",
      "valence": "0.704",
      "tempo": "74.862",
      "time_signature": "4",
      "spotify_track_popularity": "35"
    },
    {
      "SongID": "(If Loving You Is Wrong) I Don't Want To Be RightLuther Ingram",
      "Performer": "Luther Ingram",
      "Song": "(If Loving You Is Wrong) I Don't Want To Be Right",
      "spotify_genre": "['classic soul', 'memphis soul', 'southern soul']",
      "spotify_track_id": "54K7o2yNOMZYCtEDnfD6wI",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/ca9a8c56b939a8c3f70c8a17f8f6f2e6a201fd06?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "216800",
      "spotify_track_explicit": "0",
      "spotify_track_album": "(If Loving You Is Wrong) I Don't Want to Be Right",
      "danceability": "0.502",
      "energy": "0.451",
      "key": "4",
      "loudness": "-7.423",
      "mode": "0",
      "speechiness": "0.0438",
      "acousticness": "0.283",
      "instrumentalness": "0",
      "liveness": "0.154",
      "valence": "0.531",
      "tempo": "140.474",
      "time_signature": "4",
      "spotify_track_popularity": "48"
    },
    {
      "SongID": "(If There Was) Any Other WayCeline Dion",
      "Performer": "Celine Dion",
      "Song": "(If There Was) Any Other Way",
      "spotify_genre": "['canadian pop', 'dance pop']",
      "spotify_track_id": "5yh5RqpOXYN3iiJe07mNNf",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/e83a3577c394cf3cdf6454ce84928b465a6d902d?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "240093",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Unison",
      "danceability": "0.671",
      "energy": "0.784",
      "key": "7",
      "loudness": "-8.672",
      "mode": "0",
      "speechiness": "0.0322",
      "acousticness": "0.239",
      "instrumentalness": "0.0000036",
      "liveness": "0.139",
      "valence": "0.904",
      "tempo": "124.013",
      "time_signature": "4",
      "spotify_track_popularity": "28"
    },
    {
      "SongID": "(if You Add) All The Love In The WorldMac Davis",
      "Performer": "Mac Davis",
      "Song": "(if You Add) All The Love In The World",
      "spotify_genre": "['bubblegum pop', 'country rock']",
      "spotify_track_id": "1P7yXlWH1VjAlu8x1cawmb",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/e2a485c347ff96be72541be9844b5d8509a52615?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "213106",
      "spotify_track_explicit": "0",
      "spotify_track_album": "The Best Of Mac Davis",
      "danceability": "0.371",
      "energy": "0.433",
      "key": "10",
      "loudness": "-10.908",
      "mode": "1",
      "speechiness": "0.0343",
      "acousticness": "0.66",
      "instrumentalness": "0.0000133",
      "liveness": "0.103",
      "valence": "0.359",
      "tempo": "159.27",
      "time_signature": "4",
      "spotify_track_popularity": "5"
    },
    {
      "SongID": "(If You Cry) True Love, True LoveThe Drifters",
      "Performer": "The Drifters",
      "Song": "(If You Cry) True Love, True Love",
      "spotify_genre": "['adult standards', 'brill building pop', 'bubblegum pop', 'lounge', 'mellow gold', 'motown', 'rock-and-roll', 'rockabilly', 'soul']",
      "spotify_track_id": "2mfo3AK0aZzTGcXD0LnLqx",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/be6dadb63180875512f1ab3dbdd1458c5f16920b?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "141426",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Up On The Roof: The Best Of The Drifters",
      "danceability": "0.511",
      "energy": "0.236",
      "key": "0",
      "loudness": "-14.496",
      "mode": "1",
      "speechiness": "0.043",
      "acousticness": "0.67",
      "instrumentalness": "0",
      "liveness": "0.0953",
      "valence": "0.196",
      "tempo": "141.222",
      "time_signature": "4",
      "spotify_track_popularity": "16"
    },
    {
      "SongID": "(If You Let Me Make Love To You Then) Why Can't I Touch You?Ronnie Dyson",
      "Performer": "Ronnie Dyson",
      "Song": "(If You Let Me Make Love To You Then) Why Can't I Touch You?",
      "spotify_genre": "['classic soul']",
      "spotify_track_id": "5QQOXL6qvhobRG7zfjQCXW",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/087b7171b494a0ee6c3e319c3456d48192e903b7?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "203746",
      "spotify_track_explicit": "0",
      "spotify_track_album": "(If You Let Me Make Love To You Then) Why Can't I Touch You? (Expanded Edition)",
      "danceability": "0.398",
      "energy": "0.692",
      "key": "0",
      "loudness": "-8.596",
      "mode": "1",
      "speechiness": "0.045",
      "acousticness": "0.496",
      "instrumentalness": "0",
      "liveness": "0.394",
      "valence": "0.65",
      "tempo": "93.907",
      "time_signature": "4",
      "spotify_track_popularity": "20"
    },
    {
      "SongID": "(If You Want It) Do It YourselfGloria Gaynor",
      "Performer": "Gloria Gaynor",
      "Song": "(If You Want It) Do It Yourself",
      "spotify_genre": "['disco']",
      "spotify_track_id": "0ACUDVTtBKgPLo1R9Mj43L",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "170866",
      "spotify_track_explicit": "0",
      "spotify_track_album": "20th Century Masters: The Millennium Collection: Best Of Gloria Gaynor",
      "danceability": "0.686",
      "energy": "0.895",
      "key": "6",
      "loudness": "-6.731",
      "mode": "0",
      "speechiness": "0.126",
      "acousticness": "0.144",
      "instrumentalness": "0.0000118",
      "liveness": "0.197",
      "valence": "0.729",
      "tempo": "110.354",
      "time_signature": "4",
      "spotify_track_popularity": "11"
    },
    {
      "SongID": "(If You're Not In It For Love) I'm Outta Here!/The Woman In MeShania Twain",
      "Performer": "Shania Twain",
      "Song": "(If You're Not In It For Love) I'm Outta Here!/The Woman In Me",
      "spotify_genre": "['canadian country', 'canadian pop', 'country', 'country dawn', 'dance pop']",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(If You're Wondering If I Want You To) I Want You ToWeezer",
      "Performer": "Weezer",
      "Song": "(If You're Wondering If I Want You To) I Want You To",
      "spotify_genre": "['alternative rock', 'modern rock', 'permanent wave', 'pop rock', 'post-grunge', 'rock']",
      "spotify_track_id": "09aDV0TC2RfWFU5IwZfIdG",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "208773",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Raditude (Deluxe)",
      "danceability": "0.704",
      "energy": "0.869",
      "key": "11",
      "loudness": "-5.708",
      "mode": "0",
      "speechiness": "0.0442",
      "acousticness": "0.00219",
      "instrumentalness": "0.000117",
      "liveness": "0.127",
      "valence": "0.8",
      "tempo": "110.015",
      "time_signature": "4",
      "spotify_track_popularity": "51"
    },
    {
      "SongID": "(It Never Happens) In Real LifeChuck Jackson",
      "Performer": "Chuck Jackson",
      "Song": "(It Never Happens) In Real Life",
      "spotify_genre": "['classic soul', 'motown', 'northern soul', 'rhythm and blues', 'southern soul']",
      "spotify_track_id": "4qpH2D4VQfOCdV7zYkt8Hr",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/87678873155ef117cbe88aa6e9390c06e17d48f4?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "165440",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Super Hits",
      "danceability": "0.696",
      "energy": "0.459",
      "key": "3",
      "loudness": "-8.464",
      "mode": "1",
      "speechiness": "0.0303",
      "acousticness": "0.691",
      "instrumentalness": "0.0331",
      "liveness": "0.138",
      "valence": "0.849",
      "tempo": "119.069",
      "time_signature": "4",
      "spotify_track_popularity": "5"
    },
    {
      "SongID": "(It's Been A Long Time) Pretty BabyGino & Gina",
      "Performer": "Gino & Gina",
      "Song": "(It's Been A Long Time) Pretty Baby",
      "spotify_genre": "['classic canadian rock', 'mellow gold', 'soft rock', 'yacht rock']",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(It's Just) The Way That You Love MePaula Abdul",
      "Performer": "Paula Abdul",
      "Song": "(It's Just) The Way That You Love Me",
      "spotify_genre": "['dance pop', 'europop', 'new wave pop', 'pop rock', 'urban contemporary']",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(It's No) SinThe Duprees featuring Joey Vann",
      "Performer": "The Duprees featuring Joey Vann",
      "Song": "(It's No) Sin",
      "spotify_genre": "['brill building pop', 'doo-wop', 'rhythm and blues']",
      "spotify_track_id": "2iuFmbFY7FfPJtEeHmyKOE",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/dbe8aa7b490aa87f6b7c0e739e5b0a827a6c9f4e?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "162533",
      "spotify_track_explicit": "0",
      "spotify_track_album": "For Collectors Only",
      "danceability": "0.353",
      "energy": "0.377",
      "key": "7",
      "loudness": "-9.358",
      "mode": "1",
      "speechiness": "0.0294",
      "acousticness": "0.859",
      "instrumentalness": "0.0000752",
      "liveness": "0.068",
      "valence": "0.492",
      "tempo": "107.691",
      "time_signature": "3",
      "spotify_track_popularity": "11"
    },
    {
      "SongID": "(It's The Way) Nature Planned ItFour Tops",
      "Performer": "Four Tops",
      "Song": "(It's The Way) Nature Planned It",
      "spotify_genre": "['adult standards', 'brill building pop', 'classic soul', 'disco', 'funk', 'mellow gold', 'motown', 'quiet storm', 'soft rock', 'soul']",
      "spotify_track_id": "77ofWAzg1VoiK0mek1pYC0",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "227386",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Nature Planned It",
      "danceability": "0.577",
      "energy": "0.604",
      "key": "1",
      "loudness": "-8.412",
      "mode": "1",
      "speechiness": "0.0337",
      "acousticness": "0.539",
      "instrumentalness": "0.00418",
      "liveness": "0.0794",
      "valence": "0.721",
      "tempo": "92.295",
      "time_signature": "4",
      "spotify_track_popularity": "32"
    },
    {
      "SongID": "(It) Feels So GoodSteven Tyler",
      "Performer": "Steven Tyler",
      "Song": "(It) Feels So Good",
      "spotify_genre": "['modern country rock']",
      "spotify_track_id": "3xuzbqmCALn6Ua8JeOrnZl",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/401ffd88ff860f54ab5bb46b86c4be412e06e164?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "211293",
      "spotify_track_explicit": "0",
      "spotify_track_album": "(It) Feels So Good",
      "danceability": "0.738",
      "energy": "0.952",
      "key": "6",
      "loudness": "-3.386",
      "mode": "0",
      "speechiness": "0.0515",
      "acousticness": "0.0631",
      "instrumentalness": "0",
      "liveness": "0.216",
      "valence": "0.899",
      "tempo": "122",
      "time_signature": "4",
      "spotify_track_popularity": "33"
    },
    {
      "SongID": "(Just Like) Romeo & JulietThe Reflections",
      "Performer": "The Reflections",
      "Song": "(Just Like) Romeo & Juliet",
      "spotify_genre": "[]",
      "spotify_track_id": "7iSG8g8HVyGz8pgMD5cG6B",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/f5b8a46c63b94876d8ea3831f1364206ad316d62?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "127893",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Doo Wop Love",
      "danceability": "0.773",
      "energy": "0.863",
      "key": "3",
      "loudness": "-9.321",
      "mode": "1",
      "speechiness": "0.0356",
      "acousticness": "0.205",
      "instrumentalness": "0.586",
      "liveness": "0.188",
      "valence": "0.976",
      "tempo": "145.384",
      "time_signature": "4",
      "spotify_track_popularity": "28"
    },
    {
      "SongID": "(Just Like) Romeo And JulietSha Na Na",
      "Performer": "Sha Na Na",
      "Song": "(Just Like) Romeo And Juliet",
      "spotify_genre": "['hollywood']",
      "spotify_track_id": "3UDSfh7CyfmbZ2TbmafkHV",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/c58b6ee762323cadf2ef943eeb74343b748daec7?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "136240",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Grease For Peace: The Best of Sha Na Na",
      "danceability": "0.749",
      "energy": "0.738",
      "key": "3",
      "loudness": "-11.538",
      "mode": "1",
      "speechiness": "0.0388",
      "acousticness": "0.168",
      "instrumentalness": "0.0000046",
      "liveness": "0.113",
      "valence": "0.979",
      "tempo": "141.185",
      "time_signature": "4",
      "spotify_track_popularity": "11"
    },
    {
      "SongID": "(Just Like) Starting OverJohn Lennon",
      "Performer": "John Lennon",
      "Song": "(Just Like) Starting Over",
      "spotify_genre": "['album rock', 'classic rock', 'folk rock', 'mellow gold', 'rock']",
      "spotify_track_id": "5y0YreEOnQiKFAnCrcFIXz",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "236546",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Double Fantasy Stripped Down",
      "danceability": "0.701",
      "energy": "0.79",
      "key": "9",
      "loudness": "-6.16",
      "mode": "1",
      "speechiness": "0.0725",
      "acousticness": "0.301",
      "instrumentalness": "0.0000606",
      "liveness": "0.179",
      "valence": "0.421",
      "tempo": "99.104",
      "time_signature": "4",
      "spotify_track_popularity": "57"
    },
    {
      "SongID": "(Keep Feeling) FascinationThe Human League",
      "Performer": "The Human League",
      "Song": "(Keep Feeling) Fascination",
      "spotify_genre": "['art rock', 'dance rock', 'new romantic', 'new wave', 'new wave pop', 'permanent wave', 'rock', 'synthpop']",
      "spotify_track_id": "0ZfZaT7NByalxa6bct5G67",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "224733",
      "spotify_track_explicit": "0",
      "spotify_track_album": "The Very Best Of The Human League",
      "danceability": "0.711",
      "energy": "0.609",
      "key": "0",
      "loudness": "-9.042",
      "mode": "1",
      "speechiness": "0.0764",
      "acousticness": "0.381",
      "instrumentalness": "0.00000124",
      "liveness": "0.204",
      "valence": "0.674",
      "tempo": "118.132",
      "time_signature": "4",
      "spotify_track_popularity": "45"
    },
    {
      "SongID": "(Kissed You) Good NightGloriana",
      "Performer": "Gloriana",
      "Song": "(Kissed You) Good Night",
      "spotify_genre": "['contemporary country', 'country', 'country dawn', 'country road', 'modern country rock']",
      "spotify_track_id": "0Rj68IX1WqAtceUZQGk7aa",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/003038e1f66e519bbdf6c6de843bc4dbb1ecedec?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "232903",
      "spotify_track_explicit": "0",
      "spotify_track_album": "A Thousand Miles Left Behind",
      "danceability": "0.523",
      "energy": "0.747",
      "key": "11",
      "loudness": "-6.125",
      "mode": "1",
      "speechiness": "0.0292",
      "acousticness": "0.0807",
      "instrumentalness": "0",
      "liveness": "0.11",
      "valence": "0.294",
      "tempo": "118.97",
      "time_signature": "4",
      "spotify_track_popularity": "51"
    },
    {
      "SongID": "(Last Night) I Didn't Get To Sleep At AllThe 5th Dimension",
      "Performer": "The 5th Dimension",
      "Song": "(Last Night) I Didn't Get To Sleep At All",
      "spotify_genre": "['adult standards', 'brill building pop', 'bubblegum pop', 'folk', 'folk rock', 'lounge', 'mellow gold', 'motown', 'soft rock', 'sunshine pop']",
      "spotify_track_id": "6HH6fmHF2YssfVkRmzcjf0",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/e00a49dcd299576554ae634d9ee7e66763a7737c?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "192600",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Individually & Collectively",
      "danceability": "0.663",
      "energy": "0.58",
      "key": "5",
      "loudness": "-10.144",
      "mode": "0",
      "speechiness": "0.0269",
      "acousticness": "0.453",
      "instrumentalness": "0.00124",
      "liveness": "0.0963",
      "valence": "0.551",
      "tempo": "105.229",
      "time_signature": "4",
      "spotify_track_popularity": "38"
    },
    {
      "SongID": "(Lay Your Head On My) PillowTony Toni Tone",
      "Performer": "Tony Toni Tone",
      "Song": "(Lay Your Head On My) Pillow",
      "spotify_genre": "['dance pop', 'funk', 'hip pop', 'motown', 'neo soul', 'new jack swing', 'quiet storm', 'r&b', 'soul', 'urban contemporary']",
      "spotify_track_id": "0rRGYJSkI7v2VtxJv8n90m",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "372026",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Sons Of Soul",
      "danceability": "0.708",
      "energy": "0.482",
      "key": "6",
      "loudness": "-8.962",
      "mode": "0",
      "speechiness": "0.04",
      "acousticness": "0.061",
      "instrumentalness": "0.00000108",
      "liveness": "0.0689",
      "valence": "0.514",
      "tempo": "79.086",
      "time_signature": "4",
      "spotify_track_popularity": "52"
    },
    {
      "SongID": "(Let's Do) The Hully Gully TwistBill Doggett",
      "Performer": "Bill Doggett",
      "Song": "(Let's Do) The Hully Gully Twist",
      "spotify_genre": "['jazz organ', 'rhythm and blues', 'soul jazz']",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(Loneliness Made Me Realize) It's You That I NeedThe Temptations",
      "Performer": "The Temptations",
      "Song": "(Loneliness Made Me Realize) It's You That I Need",
      "spotify_genre": "['adult standards', 'brill building pop', 'classic soul', 'funk', 'memphis soul', 'motown', 'soul']",
      "spotify_track_id": "4SuPDwNadgf6fdw8v3FW5x",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "158733",
      "spotify_track_explicit": "0",
      "spotify_track_album": "With A Lot O' Soul",
      "danceability": "0.555",
      "energy": "0.37",
      "key": "0",
      "loudness": "-12.075",
      "mode": "1",
      "speechiness": "0.0311",
      "acousticness": "0.559",
      "instrumentalness": "0",
      "liveness": "0.253",
      "valence": "0.965",
      "tempo": "116.912",
      "time_signature": "4",
      "spotify_track_popularity": "20"
    },
    {
      "SongID": "(Love Is Like A) Baseball GameThe Intruders",
      "Performer": "The Intruders",
      "Song": "(Love Is Like A) Baseball Game",
      "spotify_genre": "['classic soul', 'disco', 'funk', 'motown', 'philly soul', 'quiet storm', 'soul', 'southern soul']",
      "spotify_track_id": "4Lg5z4lC7u1GPSeYvHPPi6",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/fdc5c1b14a372e1d56923af89add6dfcaefb2a74?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "165920",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Cowboys to Girls",
      "danceability": "0.654",
      "energy": "0.539",
      "key": "0",
      "loudness": "-7.825",
      "mode": "1",
      "speechiness": "0.0274",
      "acousticness": "0.748",
      "instrumentalness": "0",
      "liveness": "0.168",
      "valence": "0.849",
      "tempo": "88.978",
      "time_signature": "4",
      "spotify_track_popularity": "25"
    },
    {
      "SongID": "(Love Is) Thicker Than WaterAndy Gibb",
      "Performer": "Andy Gibb",
      "Song": "(Love Is) Thicker Than Water",
      "spotify_genre": "['adult standards', 'bubblegum pop', 'country rock', 'disco', 'mellow gold', 'soft rock']",
      "spotify_track_id": "5WdF8jm3hBNi1t9qlqdjsE",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "255960",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Flowing Rivers",
      "danceability": "0.586",
      "energy": "0.463",
      "key": "6",
      "loudness": "-9.929",
      "mode": "0",
      "speechiness": "0.0252",
      "acousticness": "0.129",
      "instrumentalness": "0.0000708",
      "liveness": "0.0757",
      "valence": "0.551",
      "tempo": "96.479",
      "time_signature": "4",
      "spotify_track_popularity": "45"
    },
    {
      "SongID": "(Love Me) Love The Life I LeadThe Fantastics",
      "Performer": "The Fantastics",
      "Song": "(Love Me) Love The Life I Lead",
      "spotify_genre": "[]",
      "spotify_track_id": "7pgKdLyCfjnrBLXJfbFLzg",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/46713b5bc4b81ac8f8793c30cf376ba787c6d52d?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "186521",
      "spotify_track_explicit": "0",
      "spotify_track_album": "The Fantastics",
      "danceability": "0.356",
      "energy": "0.549",
      "key": "9",
      "loudness": "-12.198",
      "mode": "1",
      "speechiness": "0.0574",
      "acousticness": "0.35",
      "instrumentalness": "0",
      "liveness": "0.0583",
      "valence": "0.784",
      "tempo": "78.331",
      "time_signature": "4",
      "spotify_track_popularity": "0"
    },
    {
      "SongID": "(Love Theme From) One Eyed JacksFerrante & Teicher",
      "Performer": "Ferrante & Teicher",
      "Song": "(Love Theme From) One Eyed Jacks",
      "spotify_genre": "['adult standards', 'easy listening', 'exotica', 'lounge']",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(Mama Come Quick, and Bring Your) Lickin' StickGeorge Torrence & The Naturals",
      "Performer": "George Torrence & The Naturals",
      "Song": "(Mama Come Quick, and Bring Your) Lickin' Stick",
      "spotify_genre": "[]",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(Marie's The Name) His Latest FlameElvis Presley",
      "Performer": "Elvis Presley",
      "Song": "(Marie's The Name) His Latest Flame",
      "spotify_genre": "['adult standards', 'rock-and-roll', 'rockabilly']",
      "spotify_track_id": "4qbLOU1T7xgTH87eUSkvJ1",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/a26398c1fab71f923251e6d7fc981fcb428b2f74?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "127093",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Elvis 30 #1 Hits",
      "danceability": "0.661",
      "energy": "0.917",
      "key": "4",
      "loudness": "-6.329",
      "mode": "0",
      "speechiness": "0.0375",
      "acousticness": "0.568",
      "instrumentalness": "0.00202",
      "liveness": "0.134",
      "valence": "0.893",
      "tempo": "105.289",
      "time_signature": "4",
      "spotify_track_popularity": "56"
    },
    {
      "SongID": "(Meet) The Flintstones (From \"The Flintstones\")The B.C. 52's",
      "Performer": "The B.C. 52's",
      "Song": "(Meet) The Flintstones (From \"The Flintstones\")",
      "spotify_genre": "",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(My Girl) SloopyLittle Caesar And The Consuls",
      "Performer": "Little Caesar And The Consuls",
      "Song": "(My Girl) Sloopy",
      "spotify_genre": "[]",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "(Native Girl) Elephant WalkDonald Jenkins & The Delighters",
      "Performer": "Donald Jenkins & The Delighters",
      "Song": "(Native Girl) Elephant Walk",
      "spotify_genre": "[]",
      "spotify_track_id": "",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "",
      "spotify_track_explicit": "",
      "spotify_track_album": "",
      "danceability": "",
      "energy": "",
      "key": "",
      "loudness": "",
      "mode": "",
      "speechiness": "",
      "acousticness": "",
      "instrumentalness": "",
      "liveness": "",
      "valence": "",
      "tempo": "",
      "time_signature": "",
      "spotify_track_popularity": ""
    },
    {
      "SongID": "A Long WalkJill Scott",
      "Performer": "Jill Scott",
      "Song": "A Long Walk",
      "spotify_genre": "['funk', 'hip hop', 'hip pop', 'neo soul', 'r&b', 'soul', 'urban contemporary']",
      "spotify_track_id": "1CeizRCGEYPWooEeVfmyFL",
      "spotify_track_preview_url": "",
      "spotify_track_duration_ms": "280973",
      "spotify_track_explicit": "0",
      "spotify_track_album": "Who I Jill Scott? - Word and Sound",
      "danceability": "0.667",
      "energy": "0.565",
      "key": "6",
      "loudness": "-9.452",
      "mode": "0",
      "speechiness": "0.316",
      "acousticness": "0.0699",
      "instrumentalness": "0.0000875",
      "liveness": "0.112",
      "valence": "0.281",
      "tempo": "76.165",
      "time_signature": "4",
      "spotify_track_popularity": "55"
    },
    {
      "SongID": "A Lot Of Things DifferentKenny Chesney",
      "Performer": "Kenny Chesney",
      "Song": "A Lot Of Things Different",
      "spotify_genre": "['contemporary country', 'country', 'country road']",
      "spotify_track_id": "1Hy3tvcg6l5o4codLnOC8f",
      "spotify_track_preview_url": "https://p.scdn.co/mp3-preview/60ad0070b9706890b01cb4765f332f31564a35d7?cid=b8d3901151d34489a160e3cf0ab1fa94",
      "spotify_track_duration_ms": "283866",
      "spotify_track_explicit": "0",
      "spotify_track_album": "No Shoe",
      "danceability": "0.589",
      "energy": "0.279",
      "key": "2",
      "loudness": "-13.693",
      "mode": "1",
      "speechiness": "0.0285",
      "acousticness": "0.129",
      "instrumentalness": "0.0192",
      "liveness": "0.149",
      "valence": "0.212",
      "tempo": "74.847",
      "time_signature": "4",
      "spotify_track_popularity": "36"
    }
  ]
 

  constructor(props) {
    super(props);
    this.state = {
      SongsData : this.SongsData,
      DataMusic : this.DataMusic,
    };
  }

  componentDidMount() {
    console.log(this.DataMusic)
    document.body.style.backgroundColor = "black";
    // console.log(this.state.DataMusic[0]);

  }

  Pop = () => {
    console.log("clicked Soft Btn")
    const Pop = this.DataMusic.filter(DataMusic => {
      return DataMusic.spotify_genre.includes('pop')
      
    }) 
    console.log(Pop);
      this.setState((this.state.DataMusic = Pop))
  }
  Classic = () => {
    console.log("clicked Classic Btn")
    const Classic = this.DataMusic.filter(DataMusic => {
      return DataMusic.spotify_genre.includes('classic')
      
    }) 
    console.log(Classic);
      this.setState((this.state.DataMusic = Classic))
  }
  Disco = () => {
    console.log("clicked Disco Btn")
    const Disco = this.DataMusic.filter(DataMusic => {
      return DataMusic.spotify_genre.includes('disco')
      
    }) 
    console.log(Disco);
      this.setState((this.state.DataMusic = Disco))
  }

      render(){
        return (
          <div>
            <NavbarSongs></NavbarSongs>
            <div class="d-flex justify-content-around my-3 ">
          <div class="d-flex flex-row bd-highlight my-1">
          <div className="p-2 bd-highlight ">
              <button
                type="button"
                class="btn btn-light text-white glow-on-hover mx-3 " onClick={this.Pop}
              >
                
                Pop
              </button>
            </div>

            <div className="p-2 bd-highlight ">
              <button
                type="button"
                class="btn btn-light text-white glow-on-hover mx-3 "
                onClick={this.Classic}
              >
                Classic
              </button>
            </div>
            <div className="p-2 bd-highlight ">
              <button
                type="button"
                class="btn btn-light text-white glow-on-hover mx-3 " onClick={this.Disco}
              >
                Disco
              </button>
            </div>

            

          </div>
            </div>
            <div className="container">
            <h1 className="text-white">Popular_Songs</h1>
          </div>
          <div className="container">
            <hr className="Heading"></hr>
            <div className="row">
              {
                
                  Object.keys(this.state.DataMusic || []).map((ele)=> {
                   return <div className="col-md-3 container" key= {this.state.DataMusic[ele].SongID}>
                          <div class="GlowAudio">
                            <p className="text-primary my-3 ">{this.state.DataMusic[ele].Song}</p>
                          </div>
                          <div className="container">
                            <audio controls >
                              <source src = {this.state.DataMusic[ele].spotify_track_preview_url}/>
                            </audio>
                            <hr className="Heading"></hr>
                            </div>

                   </div> 
                  })
                    
                  
                
              }
            </div>
          </div>
            <Divider></Divider>
          </div>
        )
      }
}
export default Songs;